### ISSUE TITLE
Is there way to get the url from a Video('asdasd') 

### ISSUE THREAD

**Issue by M3Horizun** [jnsougata/Ditch-YouTubeAPI#3]
I have a **Playlist()**
But I want to get the URL out of each video...
Is there a way to do so?

**Comment by jnsougata** [comment]
> I have a **Playlist()**
> But I want to get the URL out of each video...
> Is there a way to do so?

Playlist().videos will give you list of video objects ... so iterate though the list items and take item.url which will give you url for each video

**Comment by M3Horizun** [comment]
Thanks.
